module Ext
  module Integrations
    module User
    end
    
    module Organization
      def connected?
        false
      end 
      
      def fsp
        nil
      end

      def has_active_fiscally_sponsored_project?
        false
      end

      def has_fiscally_sponsored_project?
        false
      end

      def refresh_active_fs_project
      end

      def items_sold_as_reseller_during(date_range)
        []
      end

      def name_for_donations
        self.name
      end
      
      def update_kits
      end

      def sponsored_kit
        nil
      end
      
      def shows_with_sales
        # The queries are forked here because Reseller::Order redefines what
        # Order.items points to, and as a result the SQL generated by ::Order is
        # incorrect for Reseller::Order.

        standard =
          Order.
            includes(:items => { :show => :event }).
            where("orders.organization_id = ?", self.id).
            reject { |o| o.kind_of? Reseller::Order }.
            map { |o| o.items.map(&:show) }

        standard.flatten.compact.uniq.sort
      end
    end
  end
end