package_assets: on

javascripts:
  splash:
    - public/javascripts/splash/**/*.js

  vendor:
    - public/javascripts/jquery/**/*.js

  common:
    - public/javascripts/jquery_ujs.js
    - public/javascripts/application.js

  widget:
    - public/javascripts/artfully.js

stylesheets:
  splash:
    - public/stylesheets/formalize.css
    - public/stylesheets/splash/**/*.css
    - public/stylesheets/jquery/jquery.fancybox-1.3.4.css
