---
package_assets: on

s3_bucket: <%= ENV['S3_BUCKET'] %>
s3_access_key_id: <%= ENV['ACCESS_KEY_ID'] %>
s3_secret_access_key: <%= ENV['SECRET_ACCESS_KEY'] %>
ssl: true

s3_upload_files:
  - public/404.html
  - public/422.html
  - public/500.html
  - public/apple-touch-icon.png
  - public/favicon.ico
  - public/robots.txt
  - public/forms/**/*
  - public/stylesheets/formalize.css
  - public/stylesheets/printing.css
  - public/stylesheets/reset.css
  - public/stylesheets/themes/default.css
  - public/javascripts/artfully.js

javascripts:
  splash:
    - public/javascripts/splash/**/*.js

  vendor:
    - public/javascripts/jquery/**/*.js

  application:
    - public/javascripts/jquery_ujs.js
    - public/javascripts/application.js

  custom:
    - public/javascripts/custom/**/*.js

  store:
    - public/javascripts/jquery/jquery.mask-money.js
    - public/javascripts/jquery/jquery.formalize.js
    - public/javascripts/jquery_ujs.js
    - public/javascripts/store/jquery.validate.js
    - public/javascripts/jquery/jquery.formatCurrency-1.4.0.min.js
    - public/javascripts/store/**/*.js

stylesheets:
  splash:
    - public/stylesheets/formalize.css
    - public/stylesheets/splash/**/*.css
    - public/stylesheets/jquery/jquery.fancybox-1.3.4.css

  application:
    - public/stylesheets/reset.css
    - public/stylesheets/formalize.css
    - public/stylesheets/application.css

  vendor:
    - public/stylesheets/jquery/jquery.gritter.css
    - public/stylesheets/jquery/jquery-ui.css
    - public/stylesheets/jquery/jquery.visualize.css
    - public/stylesheets/jquery/fullcalendar.css

  printing:
    - public/stylesheets/printing.css

  themes_default:
    - public/stylesheets/themes/default.css

  store:
    - public/stylesheets/reset.css
    - public/stylesheets/formalize.css
    - public/stylesheets/cart.css
    - public/stylesheets/store.css