package_assets: on

s3_bucket: <%= ENV['S3_BUCKET'] %>
s3_access_key_id: <%= ENV['ACCESS_KEY_ID'] %>
s3_secret_access_key: <%= ENV['SECRET_ACCESS_KEY'] %>

# S3 Upload Credentials
s3_upload_files:
  - public/404.html
  - public/422.html
  - public/500.html
  - public/apple-touch-icon.png
  - public/favicon.ico
  - public/robots.txt
  - public/forms/**/*
  - public/stylesheets/formalize.css
  - public/stylesheets/printing.css
  - public/stylesheets/reset.css


javascripts:
  splash:
    - public/javascripts/splash/**/*.js

  vendor:
    - public/javascripts/jquery/**/*.js

  application:
    - public/javascripts/jquery_ujs.js
    - public/javascripts/application.js
    - public/javascripts/datatables.js

  custom:
    - public/javascripts/custom/**/*.js

  widget:
    - public/javascripts/jquery/jquery.mask-money.js
    - public/javascripts/jquery/jquery.formalize.js
    - public/javascripts/jquery_ujs.js

stylesheets:
  splash:
    - public/stylesheets/formalize.css
    - public/stylesheets/splash/**/*.css
    - public/stylesheets/jquery/jquery.fancybox-1.3.4.css

  application:
    - public/stylesheets/application.css
    - public/stylesheets/formalize.css

  vendor:
    - public/stylesheets/jquery/jquery.gritter.css
    - public/stylesheets/jquery/jquery.ui.css
    - public/stylesheets/jquery/jquery.visualize.css
    - public/stylesheets/jquery/fullcalendar.css

  printing:
    - public/stylesheets/printing.css

  widget:
    - public/stylesheets/themes/default.css
    - public/stylesheets/formalize.css
